<?php

namespace AppBundle\Repository;

/**
 * filmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class filmsRepository extends \Doctrine\ORM\EntityRepository
{
}
