<?php

namespace AppBundle\Repository;

/**
 * seriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seriesRepository extends \Doctrine\ORM\EntityRepository
{
}
